# Generated by Django 5.2.11 on 2026-02-25 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('CategoryID', models.AutoField(primary_key=True, serialize=False)),
                ('CategoryName', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CustomerID', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('FullName', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=150, unique=True)),
                ('Password', models.CharField(blank=True, max_length=255, null=True)),
                ('PhoneNumber', models.CharField(blank=True, max_length=15, null=True)),
                ('Address', models.CharField(blank=True, max_length=255, null=True)),
                ('Avatar', models.CharField(blank=True, max_length=500, null=True)),
                ('GoogleID', models.CharField(blank=True, max_length=100, null=True)),
                ('FacebookID', models.CharField(blank=True, max_length=100, null=True)),
                ('LoginType', models.CharField(choices=[('normal', 'Normal'), ('google', 'Google'), ('facebook', 'Facebook')], default='normal', max_length=20)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('StaffID', models.AutoField(primary_key=True, serialize=False)),
                ('FullName', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=150, unique=True)),
                ('Password', models.CharField(max_length=255)),
                ('Role', models.CharField(choices=[('Admin', 'Admin'), ('Staff', 'Staff'), ('Unentitled', 'Unentitled')], max_length=50)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Staff',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OrderID', models.AutoField(primary_key=True, serialize=False)),
                ('OrderDate', models.DateTimeField(auto_now_add=True)),
                ('TotalAmount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('Status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Shipping', 'Shipping'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50)),
                ('ShippingAddress', models.CharField(max_length=255)),
                ('CustomerID', models.ForeignKey(db_column='CustomerID', on_delete=django.db.models.deletion.CASCADE, to='phone.customer')),
            ],
            options={
                'db_table': 'Order',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('PaymentID', models.AutoField(primary_key=True, serialize=False)),
                ('Method', models.CharField(choices=[('COD', 'COD'), ('Bank Transfer', 'Bank Transfer'), ('E-Wallet', 'E-Wallet')], max_length=50)),
                ('Status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed')], default='Pending', max_length=50)),
                ('PaidAt', models.DateTimeField(blank=True, null=True)),
                ('OrderID', models.ForeignKey(db_column='OrderID', on_delete=django.db.models.deletion.CASCADE, to='phone.order')),
            ],
            options={
                'db_table': 'Payment',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductID', models.AutoField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=200)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Brand', models.CharField(blank=True, max_length=100, null=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('CategoryID', models.ForeignKey(db_column='CategoryID', on_delete=django.db.models.deletion.CASCADE, to='phone.category')),
            ],
            options={
                'db_table': 'Product',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('ImageID', models.AutoField(primary_key=True, serialize=False)),
                ('ImageUrl', models.CharField(max_length=500)),
                ('IsPrimary', models.BooleanField(default=False)),
                ('ProductID', models.ForeignKey(db_column='ProductID', on_delete=django.db.models.deletion.CASCADE, to='phone.product')),
            ],
            options={
                'db_table': 'ProductImage',
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('VariantID', models.AutoField(primary_key=True, serialize=False)),
                ('Cpu', models.CharField(blank=True, max_length=100, null=True)),
                ('OperatingSystem', models.CharField(blank=True, max_length=50, null=True)),
                ('ScreenSize', models.CharField(blank=True, max_length=50, null=True)),
                ('ScreenTechnology', models.CharField(blank=True, max_length=50, null=True)),
                ('RefreshRate', models.CharField(blank=True, max_length=50, null=True)),
                ('Battery', models.CharField(blank=True, max_length=50, null=True)),
                ('ChargingSpeed', models.CharField(blank=True, max_length=50, null=True)),
                ('Storage', models.CharField(blank=True, max_length=50, null=True)),
                ('Ram', models.CharField(blank=True, max_length=50, null=True)),
                ('FrontCamera', models.CharField(blank=True, max_length=500, null=True)),
                ('RearCamera', models.CharField(blank=True, max_length=500, null=True)),
                ('Color', models.CharField(blank=True, max_length=50, null=True)),
                ('Weights', models.CharField(blank=True, max_length=50, null=True)),
                ('Updates', models.CharField(blank=True, max_length=50, null=True)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('StockQuantity', models.IntegerField(default=0)),
                ('ProductID', models.ForeignKey(db_column='ProductID', on_delete=django.db.models.deletion.CASCADE, to='phone.product')),
            ],
            options={
                'db_table': 'ProductVariant',
            },
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('ShippingID', models.AutoField(primary_key=True, serialize=False)),
                ('ShippingProvider', models.CharField(blank=True, max_length=100, null=True)),
                ('TrackingCode', models.CharField(blank=True, max_length=100, null=True)),
                ('Status', models.CharField(choices=[('Waiting', 'Waiting'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered'), ('Failed', 'Failed')], default='Waiting', max_length=50)),
                ('EstimatedDelivery', models.DateField(blank=True, null=True)),
                ('OrderID', models.ForeignKey(db_column='OrderID', on_delete=django.db.models.deletion.CASCADE, to='phone.order')),
            ],
            options={
                'db_table': 'Shipping',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('UnitPrice', models.DecimalField(decimal_places=2, max_digits=18)),
                ('OrderID', models.ForeignKey(db_column='OrderID', on_delete=django.db.models.deletion.CASCADE, to='phone.order')),
                ('VariantID', models.ForeignKey(db_column='VariantID', on_delete=django.db.models.deletion.CASCADE, to='phone.productvariant')),
            ],
            options={
                'db_table': 'OrderDetail',
                'unique_together': {('OrderID', 'VariantID')},
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(default=1)),
                ('CustomerID', models.ForeignKey(db_column='CustomerID', on_delete=django.db.models.deletion.CASCADE, to='phone.customer')),
                ('VariantID', models.ForeignKey(db_column='VariantID', on_delete=django.db.models.deletion.CASCADE, to='phone.productvariant')),
            ],
            options={
                'db_table': 'Cart',
                'unique_together': {('CustomerID', 'VariantID')},
            },
        ),
    ]
