# Generated by Django 5.2.11 on 2026-03-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Avatar',
            field=models.TextField(blank=True, null=True),
        ),
    ]
