# Generated by Django 5.2.11 on 2026-02-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phone", "0002_alter_cart_id_alter_orderdetail_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="Role",
            field=models.CharField(
                choices=[
                    ("Admin", "Admin"),
                    ("Staff", "Staff"),
                    ("Unentitled", "Unentitled"),
                ],
                max_length=50,
            ),
        ),
    ]
