# Generated by Django 5.2.11 on 2026-03-04 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0002_alter_customer_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='Avatar',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
