# Generated by Django 5.2.11 on 2026-03-04 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0003_staff_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
