# Generated by Django 5.2.11 on 2026-03-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0004_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='Image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
