# Generated by Django 5.2.11 on 2026-03-05 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0005_productvariant_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('AddressID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=300)),
                ('CustomerID', models.ForeignKey(db_column='CustomerID', on_delete=django.db.models.deletion.CASCADE, to='phone.customer')),
            ],
            options={
                'db_table': 'CustomerAddress',
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('VoucherID', models.AutoField(primary_key=True, serialize=False)),
                ('Code', models.CharField(max_length=50, unique=True)),
                ('Type', models.CharField(max_length=10)),
                ('Value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Scope', models.CharField(default='all', max_length=20)),
                ('MinOrder', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('MaxDiscount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('StartDate', models.DateField(blank=True, null=True)),
                ('EndDate', models.DateField(blank=True, null=True)),
                ('UsageLimit', models.IntegerField(blank=True, null=True)),
                ('UsedCount', models.IntegerField(default=0)),
                ('IsActive', models.BooleanField(default=True)),
                ('CategoryID', models.ForeignKey(blank=True, db_column='CategoryID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='phone.category')),
                ('ProductID', models.ForeignKey(blank=True, db_column='ProductID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='phone.product')),
            ],
            options={
                'db_table': 'Voucher',
            },
        ),
    ]
