# Generated by Django 5.2.11 on 2026-03-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0006_customeraddress_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='order',
            name='PaymentMethod',
            field=models.CharField(default='cod', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='StatusNote',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
