# Generated by Django 5.2.11 on 2026-03-05 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0007_order_discount_order_paymentmethod_order_statusnote_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('ReturnID', models.AutoField(primary_key=True, serialize=False)),
                ('Reason', models.TextField()),
                ('Status', models.CharField(choices=[('Pending', 'Chờ xét duyệt'), ('Approved', 'Đã chấp nhận'), ('Rejected', 'Đã từ chối'), ('Returning', 'Đang nhận hàng hoàn về'), ('Completed', 'Hoàn tất')], default='Pending', max_length=20)),
                ('AdminNote', models.CharField(blank=True, max_length=500, null=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('OrderID', models.OneToOneField(db_column='OrderID', on_delete=django.db.models.deletion.CASCADE, to='phone.order')),
            ],
            options={
                'db_table': 'ReturnRequest',
            },
        ),
        migrations.CreateModel(
            name='ReturnMedia',
            fields=[
                ('MediaID', models.AutoField(primary_key=True, serialize=False)),
                ('Url', models.CharField(max_length=500)),
                ('MediaType', models.CharField(default='image', max_length=10)),
                ('ReturnID', models.ForeignKey(db_column='ReturnID', on_delete=django.db.models.deletion.CASCADE, to='phone.returnrequest')),
            ],
            options={
                'db_table': 'ReturnMedia',
            },
        ),
    ]
