# Generated by Django 5.2.11 on 2026-03-05 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0008_returnrequest_returnmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('PostID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=300)),
                ('Category', models.CharField(default='Mẹo vặt', max_length=50)),
                ('Blocks', models.TextField(default='[]')),
                ('Author', models.CharField(default='Admin', max_length=100)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Post',
            },
        ),
        migrations.CreateModel(
            name='ProductContent',
            fields=[
                ('ContentID', models.AutoField(primary_key=True, serialize=False)),
                ('Blocks', models.TextField(default='[]')),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('ProductID', models.OneToOneField(db_column='ProductID', on_delete=django.db.models.deletion.CASCADE, to='phone.product')),
            ],
            options={
                'db_table': 'ProductContent',
            },
        ),
    ]
