# Generated by Django 5.2.11 on 2026-03-07 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0009_post_productcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='VariantID',
            field=models.ForeignKey(blank=True, db_column='VariantID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers', to='phone.productvariant'),
        ),
    ]
