# Generated by Django 5.2.11 on 2026-03-10 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0011_adminreply_comment_review_reviewmedia_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ActualDelivery',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='EstimatedDelivery',
            field=models.DateField(blank=True, null=True),
        ),
    ]
