# Generated by Django 5.2.11 on 2026-03-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0012_order_actualdelivery_order_estimateddelivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='ScreenTechnology',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
