# Generated by Django 5.2.11 on 2026-03-15 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0014_review_review_rating_1_to_5'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('BannerID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(blank=True, default='', max_length=200)),
                ('Page', models.CharField(choices=[('all', 'Tất cả trang'), ('home', 'Trang chủ'), ('product', 'Trang sản phẩm'), ('blog', 'Trang blog')], default='all', max_length=20)),
                ('IsActive', models.BooleanField(default=True)),
                ('AutoPlay', models.BooleanField(default=True)),
                ('Interval', models.IntegerField(default=4000)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Banner',
            },
        ),
        migrations.CreateModel(
            name='BannerItem',
            fields=[
                ('BannerItemID', models.AutoField(primary_key=True, serialize=False)),
                ('MediaType', models.CharField(choices=[('image', 'Hình ảnh'), ('video', 'Video')], default='image', max_length=10)),
                ('MediaUrl', models.CharField(max_length=1000)),
                ('PublicID', models.CharField(blank=True, default='', max_length=300)),
                ('LinkUrl', models.CharField(blank=True, default='', max_length=500)),
                ('Caption', models.CharField(blank=True, default='', max_length=300)),
                ('VideoMode', models.CharField(blank=True, choices=[('autoplay', 'Autoplay muted, loop'), ('click', 'Click để phát')], default='autoplay', max_length=10)),
                ('SortOrder', models.IntegerField(default=0)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('BannerID', models.ForeignKey(db_column='BannerID', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='phone.banner')),
            ],
            options={
                'db_table': 'BannerItem',
                'ordering': ['SortOrder', 'BannerItemID'],
            },
        ),
    ]
