# Generated by Django 5.2.11 on 2026-03-15 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0015_banner_banneritem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banneritem',
            name='VideoMode',
            field=models.CharField(blank=True, choices=[('autoplay', 'Autoplay muted'), ('click', 'Click để phát')], default='autoplay', max_length=10),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('LogID', models.AutoField(primary_key=True, serialize=False)),
                ('Action', models.CharField(choices=[('login', 'Đăng nhập'), ('logout', 'Đăng xuất'), ('create_product', 'Tạo sản phẩm'), ('update_product', 'Sửa sản phẩm'), ('delete_product', 'Xóa sản phẩm'), ('import_stock', 'Nhập hàng'), ('add_variants', 'Thêm biến thể'), ('update_variant', 'Sửa biến thể'), ('create_category', 'Tạo danh mục'), ('update_category', 'Sửa danh mục'), ('delete_category', 'Xóa danh mục'), ('create_staff', 'Tạo nhân viên'), ('update_staff_role', 'Đổi quyền nhân viên'), ('delete_staff', 'Xóa nhân viên'), ('create_voucher', 'Tạo voucher'), ('update_voucher', 'Sửa voucher'), ('delete_voucher', 'Xóa voucher'), ('deactivate_voucher', 'Tắt voucher'), ('update_order', 'Cập nhật đơn hàng'), ('cancel_order', 'Hủy đơn hàng'), ('process_return', 'Xử lý trả hàng'), ('create_post', 'Tạo bài viết'), ('update_post', 'Sửa bài viết'), ('delete_post', 'Xóa bài viết'), ('create_banner', 'Tạo banner'), ('update_banner', 'Sửa banner'), ('delete_banner', 'Xóa banner'), ('add_banner_item', 'Thêm item banner'), ('delete_banner_item', 'Xóa item banner')], max_length=50)),
                ('Detail', models.TextField(blank=True, default='')),
                ('IPAddress', models.CharField(blank=True, default='', max_length=45)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('StaffID', models.ForeignKey(blank=True, db_column='StaffID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='phone.staff')),
            ],
            options={
                'db_table': 'ActivityLog',
                'ordering': ['-CreatedAt'],
            },
        ),
    ]
