# Generated by Django 5.2.11 on 2026-03-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0016_alter_banneritem_videomode_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='Action',
            field=models.CharField(choices=[('login', 'Đăng nhập'), ('logout', 'Đăng xuất'), ('create_product', 'Tạo sản phẩm'), ('update_product', 'Sửa sản phẩm'), ('delete_product', 'Xóa sản phẩm'), ('import_stock', 'Nhập hàng'), ('add_variants', 'Thêm biến thể'), ('update_variant', 'Sửa biến thể'), ('create_category', 'Tạo danh mục'), ('update_category', 'Sửa danh mục'), ('delete_category', 'Xóa danh mục'), ('create_staff', 'Tạo nhân viên'), ('update_staff_role', 'Đổi quyền nhân viên'), ('delete_staff', 'Xóa nhân viên'), ('create_voucher', 'Tạo voucher'), ('update_voucher', 'Sửa voucher'), ('delete_voucher', 'Xóa voucher'), ('deactivate_voucher', 'Tắt voucher'), ('update_order', 'Cập nhật đơn hàng'), ('cancel_order', 'Hủy đơn hàng'), ('process_return', 'Xử lý trả hàng'), ('create_post', 'Tạo bài viết'), ('update_post', 'Sửa bài viết'), ('delete_post', 'Xóa bài viết'), ('create_banner', 'Tạo banner'), ('update_banner', 'Sửa banner'), ('delete_banner', 'Xóa banner'), ('add_banner_item', 'Thêm item banner'), ('delete_banner_item', 'Xóa item banner'), ('reply_comment', 'Trả lời bình luận'), ('reply_review', 'Trả lời đánh giá'), ('delete_reply', 'Xóa phản hồi')], max_length=50),
        ),
    ]
