# Generated by Django 5.2.11 on 2026-03-20 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0017_alter_activitylog_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerActivityLog',
            fields=[
                ('LogID', models.AutoField(primary_key=True, serialize=False)),
                ('Action', models.CharField(choices=[('register', 'Đăng ký tài khoản'), ('login', 'Đăng nhập'), ('login_google', 'Đăng nhập Google'), ('login_facebook', 'Đăng nhập Facebook'), ('logout', 'Đăng xuất'), ('forgot_password', 'Yêu cầu đặt lại mật khẩu'), ('reset_password', 'Đặt lại mật khẩu'), ('change_password', 'Đổi mật khẩu'), ('update_profile', 'Cập nhật thông tin cá nhân'), ('upload_avatar', 'Đổi ảnh đại diện'), ('create_address', 'Thêm địa chỉ'), ('update_address', 'Sửa địa chỉ'), ('delete_address', 'Xóa địa chỉ'), ('create_order', 'Đặt hàng'), ('cancel_order', 'Hủy đơn hàng'), ('create_return', 'Yêu cầu hoàn trả'), ('apply_voucher', 'Áp dụng voucher'), ('create_review', 'Viết đánh giá'), ('update_review', 'Sửa đánh giá'), ('delete_review', 'Xóa đánh giá'), ('create_comment', 'Viết bình luận'), ('delete_comment', 'Xóa bình luận'), ('like', 'Thích'), ('unlike', 'Bỏ thích'), ('search_text', 'Tìm kiếm văn bản'), ('search_image', 'Tìm kiếm bằng ảnh'), ('view_product', 'Xem sản phẩm')], max_length=30)),
                ('Detail', models.TextField(blank=True, default='')),
                ('IPAddress', models.CharField(blank=True, default='', max_length=45)),
                ('UserAgent', models.CharField(blank=True, default='', max_length=300)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('CustomerID', models.ForeignKey(blank=True, db_column='CustomerID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='phone.customer')),
            ],
            options={
                'db_table': 'CustomerActivityLog',
                'ordering': ['-CreatedAt'],
                'indexes': [models.Index(fields=['CustomerID', '-CreatedAt'], name='idx_clog_customer_time'), models.Index(fields=['Action'], name='idx_clog_action')],
            },
        ),
    ]
