# Generated by Django 5.2.11 on 2026-03-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0018_customeractivitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminreply',
            name='Media',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AddField(
            model_name='comment',
            name='Media',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
