# Generated by Django 5.2.11 on 2026-03-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0019_adminreply_media_comment_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='IsActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='IsActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='IsActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='IsActive',
            field=models.BooleanField(default=True),
        ),
    ]
