# Generated by Django 5.2.11 on 2026-03-22 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0020_category_isactive_post_isactive_product_isactive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='IsActive',
            field=models.BooleanField(default=True),
        ),
    ]
