# Generated by Django 5.2.11 on 2026-03-22 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0021_customer_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='DistrictCode',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='DistrictName',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='IsDefault',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='ProvinceCode',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='ProvinceName',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='WardCode',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='WardName',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
